"""
Takes as input the .out match observations file generated by stevearc's
testing framework and outputs a file containing only our match observations.
They are still encrypted and must be decrypted using the Encryption class
in our bot's package.
"""

INPUT = 'input.out'
OUTPUT = 'output.txt'
TEAM = 'A'

def main():
  fi = open(INPUT, 'r')
  fo = open(OUTPUT, 'w')
  for l in fi:
    if l[1] != TEAM:
      continue
    fo.write(l)
  fi.close()
  fo.close()

if __name__ == '__main__':
  main()
